# Dockerfile.serving
FROM python:3.10-slim

WORKDIR /app

# copy codes
COPY app.py requirements.txt ./ 

# install dependency
RUN pip3 install --no-cache-dir -r requirements.txt


EXPOSE 8080

CMD ["python", "app.py"]
